SRCS += printf/ft_printf.c printf/string_length.c \
		printf/writer.c printf/ft_printf.c printf/parser.c \
		printf/parser_token.c printf/parser_padding.c \
		printf/parser_write_string.c printf/parser_hash_flag.c \
		printf/writer_write_format.c printf/parser_parse_format_string.c \
		printf/parser_write_nbr.c
