[build-system]
requires= ["setuptools", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "push_swap"
version = "0.1.0"
dependencies = []

[project.scripts]
push_swap = "push_swap.main:main"
